services:
  # ========================================================================
  # Airflow (orchestrator)
  # ========================================================================
  airflow-postgres:
    image: postgres:16-alpine
    container_name: latam_airflow_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  airflow-init:
      image: apache/airflow:2.9.1
      container_name: latam_airflow_init
      restart: "no"
      depends_on:
        airflow-postgres:
          condition: service_healthy
      env_file:
        - .env
      environment:
        AIRFLOW__CORE__EXECUTOR: LocalExecutor
        AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
        AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      volumes:
        - ./requirements.txt:/requirements.txt
      entrypoint: /bin/bash
      command: -c "
        pip install -r /requirements.txt &&
        airflow db migrate &&
        airflow users create \
          --username ${AIRFLOW_ADMIN_USERNAME} \
          --password ${AIRFLOW_ADMIN_PASSWORD} \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email ${AIRFLOW_ADMIN_EMAIL}"

  airflow-scheduler:
    image: apache/airflow:2.9.1
    container_name: latam_airflow_scheduler
    restart: unless-stopped
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__PARALLELISM: 4
      AIRFLOW__CORE__MAX_ACTIVE_TASKS_PER_DAG: 4
      PYTHONPATH: /opt/airflow/pipeline
      AIRFLOW_VAR_RAW_DATA_PATH: ${RAW_DATA_PATH}
      # Variables Airflow auto-créées
      # Neon _________________________________________________
      AIRFLOW_VAR_DB_HOST: ${DB_HOST}
      AIRFLOW_VAR_DB_NAME: ${DB_NAME}
      AIRFLOW_VAR_DB_USER: ${DB_USER}
      AIRFLOW_VAR_DB_PASSWORD: ${DB_PASSWORD}
      AIRFLOW_VAR_DB_SSLMODE: ${DB_SSLMODE}
      AIRFLOW_VAR_DB_CHANNELBIDING: ${DB_CHANNELBIDING}
      # Backblaze ____________________________________________
      AIRFLOW_VAR_KEY_ID: ${KEY_ID}
      AIRFLOW_VAR_APPLICATION_KEY: ${APPLICATION_KEY}
      AIRFLOW_VAR_BUCKET_NAME: ${BUCKET_NAME}
      # APIs _________________________________________________
      AIRFLOW_VAR_JSEARCH_APP_KEY: ${JSEARCH_APP_KEY}
      AIRFLOW_VAR_JSEARCH_APP_HOST: ${JSEARCH_APP_HOST}
      AIRFLOW_VAR_CAREERJET_APP_KEY: ${CAREERJET_APP_KEY}
      AIRFLOW_VAR_CAREERJET_USER_AGENT: ${CAREERJET_USER_AGENT}
      AIRFLOW_VAR_CAREERJET_REFERER: ${CAREERJET_REFERER}
      AIRFLOW_VAR_SERVER_IP: ${SERVER_IP}
      # LLM __________________________________________________
      AIRFLOW_VAR_MISTRAL_API_KEY: ${MISTRAL_API_KEY}
      AIRFLOW_VAR_GEMINI_API_KEY: ${GEMINI_API_KEY}
      AIRFLOW_VAR_MAPS_APP_KEY: ${MAPS_APP_KEY}
    volumes:
      - ./ingestion/airflow/dags:/opt/airflow/dags
      - ./ingestion/python/src:/opt/airflow/pipeline
      - ./ingestion/logs:/opt/airflow/logs
      - ./ingestion/raw:/opt/airflow/raw
      - ./ingestion/config:/opt/airflow/config
    command: scheduler

  airflow-webserver:
    image: apache/airflow:2.9.1
    container_name: latam_airflow_webserver
    restart: unless-stopped
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      PYTHONPATH: /opt/airflow/pipeline   # ← pointe vers python/src/
    volumes:
      - ./ingestion/airflow/dags:/opt/airflow/dags       # ← DAGs
      - ./ingestion/python/src:/opt/airflow/pipeline     # ← scripts Python
      - ./ingestion/logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    command: webserver






  
volumes:
  airflow_postgres_data: