fake_job_offers = [
    {
        "id_offer": "JOB-0001",
        "api_source": "adzuna",
        "job_title": "Backend Python Developer",
        "offer_description": "Develop and maintain REST APIs using Python and FastAPI.",
        "contract_type": "CDI",
        "is_remote": True,
        "alternative_job_titles": ["Python Engineer", "Backend Engineer"],
        "offer_languages": ["English"],
        "seniority": "Mid",
        "skills_languages": ["Python", "SQL"],
        "skills_frameworks": ["FastAPI", "Docker"],
        "skills_aptitudes": ["API Design", "Database Optimization"],
        "skills_soft": ["Teamwork", "Communication"],
        "score_relevancy": 0.92,
        "explanations": "Excellent match for Python backend profile.",
        "company_name": "TechNova",
        "website": "https://technova.io",
        "primary_type": "Software company_name",
        "city": "Montreal",
        "country": "Canada",
        "lat": 45.5017,
        "lon": -73.5673,
        "offer_url": "https://jobs.technova.io/1",
        "published_at": "2026-06-01T09:00:00Z",
        "collected_at": "2026-06-01T10:00:00Z"
    },
    {
        "id_offer": "JOB-0002",
        "api_source": "linkedin",
        "job_title": "Data Engineer",
        "offer_description": "Build scalable ETL pipelines and data warehouses.",
        "contract_type": "Permanent",
        "is_remote": False,
        "alternative_job_titles": ["ETL Engineer", "Big Data Engineer"],
        "offer_languages": ["English", "French"],
        "seniority": "Senior",
        "skills_languages": ["Python", "SQL"],
        "skills_frameworks": ["Spark", "Airflow"],
        "skills_aptitudes": ["Data Modeling", "ETL"],
        "skills_soft": ["Problem Solving"],
        "score_relevancy": 0.88,
        "explanations": "Strong match for data engineering skills.",
        "company_name": "DataFlow",
        "website": "https://dataflow.com",
        "primary_type": "Consulting",
        "city": "Toronto",
        "country": "Canada",
        "lat": 43.6532,
        "lon": -79.3832,
        "offer_url": "https://jobs.dataflow.com/2",
        "published_at": "2026-06-02T08:00:00Z",
        "collected_at": "2026-06-02T09:00:00Z"
    },
    {
        "id_offer": "JOB-0003",
        "api_source": "indeed",
        "job_title": "Frontend React Developer",
        "offer_description": "Create modern web applications with React.",
        "contract_type": "CDI",
        "is_remote": True,
        "alternative_job_titles": ["Frontend Engineer"],
        "offer_languages": ["English"],
        "seniority": "Junior",
        "skills_languages": ["JavaScript", "TypeScript"],
        "skills_frameworks": ["React", "Redux"],
        "skills_aptitudes": ["UI Development"],
        "skills_soft": ["Creativity"],
        "score_relevancy": 0.81,
        "explanations": "Relevant frontend opportunity.",
        "company_name": "WebCraft",
        "website": "https://webcraft.io",
        "primary_type": "Startup",
        "city": "Vancouver",
        "country": "Canada",
        "lat": 49.2827,
        "lon": -123.1207,
        "offer_url": "https://webcraft.io/jobs/3",
        "published_at": "2026-06-03T12:00:00Z",
        "collected_at": "2026-06-03T12:15:00Z"
    },
    {
        "id_offer": "JOB-0004",
        "api_source": "jooble",
        "job_title": "DevOps Engineer",
        "offer_description": "Manage cloud infrastructure and CI/CD pipelines.",
        "contract_type": "Contract",
        "is_remote": True,
        "alternative_job_titles": ["Cloud Engineer"],
        "offer_languages": ["English"],
        "seniority": "Senior",
        "skills_languages": ["Bash", "Python"],
        "skills_frameworks": ["Kubernetes", "Terraform"],
        "skills_aptitudes": ["Infrastructure as Code"],
        "skills_soft": ["Autonomy"],
        "score_relevancy": 0.90,
        "explanations": "Strong infrastructure fit.",
        "company_name": "CloudOps",
        "website": "https://cloudops.ca",
        "primary_type": "IT Services",
        "city": "Calgary",
        "country": "Canada",
        "lat": 51.0447,
        "lon": -114.0719,
        "offer_url": "https://cloudops.ca/jobs/4",
        "published_at": "2026-06-04T10:00:00Z",
        "collected_at": "2026-06-04T10:05:00Z"
    },
    {
        "id_offer": "JOB-0005",
        "api_source": "linkedin",
        "job_title": "Machine Learning Engineer",
        "offer_description": "Deploy ML models into production.",
        "contract_type": "CDI",
        "is_remote": True,
        "alternative_job_titles": ["AI Engineer"],
        "offer_languages": ["English"],
        "seniority": "Mid",
        "skills_languages": ["Python"],
        "skills_frameworks": ["PyTorch", "TensorFlow"],
        "skills_aptitudes": ["Model Deployment"],
        "skills_soft": ["Analytical Thinking"],
        "score_relevancy": 0.95,
        "explanations": "Excellent AI/ML match.",
        "company_name": "DeepVision",
        "website": "https://deepvision.ai",
        "primary_type": "AI company_name",
        "city": "Ottawa",
        "country": "Canada",
        "lat": 45.4215,
        "lon": -75.6972,
        "offer_url": "https://deepvision.ai/jobs/5",
        "published_at": "2026-06-05T11:00:00Z",
        "collected_at": "2026-06-05T11:30:00Z"
    }
]

# Génération automatique des 15 lignes restantes
for i in range(6, 21):
    fake_job_offers.append({
        "id_offer": f"JOB-{i:04d}",
        "api_source": ["linkedin", "indeed", "adzuna", "jooble"][i % 4],
        "job_title": [
            "Software Engineer",
            "Backend Developer",
            "Full Stack Developer",
            "Data Scientist",
            "Cybersecurity Analyst"
        ][i % 5],
        "offer_description": f"Sample description for job offer {i}.",
        "contract_type": ["CDI", "Permanent", "Contract"][i % 3],
        "is_remote": i % 2 == 0,
        "alternative_job_titles": ["Developer", "Engineer"],
        "offer_languages": ["English", "French"] if i % 3 == 0 else ["English"],
        "seniority": ["Junior", "Mid", "Senior"][i % 3],
        "skills_languages": ["Python", "SQL"],
        "skills_frameworks": ["Docker", "Kubernetes"],
        "skills_aptitudes": ["Problem Solving", "System Design"],
        "skills_soft": ["Communication", "Teamwork"],
        "score_relevancy": round(0.70 + (i * 0.01), 2),
        "explanations": f"Generated explanation for offer {i}.",
        "company_name": f"company_name{i}",
        "website": f"https://company_name{i}.com",
        "primary_type": "Technology",
        "city": ["Montreal", "Toronto", "Vancouver", "Ottawa"][i % 4],
        "country": "Canada",
        "lat": 45.0 + (i * 0.1),
        "lon": -73.0 - (i * 0.1),
        "offer_url": f"https://company_name{i}.com/jobs/{i}",
        "published_at": f"2026-06-{i:02d}T09:00:00Z",
        "collected_at": f"2026-06-{i:02d}T09:15:00Z"
    })